// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#pragma once

// Conditional graph regions for HIP/ROCm.
//
// ROCm has no equivalent of CUDA's conditional graph node
// (CU_GRAPH_NODE_TYPE_CONDITIONAL), so Warp's capture_while / capture_if cannot
// be expressed the way warp.cu builds them: cudaGraphConditionalHandleCreate is
// bound for HIP only to return hipErrorNotSupported, and cudaGraphAddNode and
// cudaGraphNodeParams are not bound at all.
//
// This header adapts Warp's conditional-node contract onto hipgraph_cond, which
// approximates the same semantics with a static unroll: the loop body is emitted
// max_iters times into the parent graph, with a device-side refresh of the
// condition between copies, and no host round trip (a host poll is illegal
// inside a capture).
//
// READ THIS BEFORE TRUSTING THE SEMANTICS. The unroll is predicated only if the
// body cooperates. hipgraph_cond.cu::cloneGraphInto copies each body node's
// params verbatim and injects nothing, so a copy is skipped at run time only
// when the body's own kernels test the region's guard word
// (hipGraphCondSetGuard / hipGraphCondHandleGetDevicePtr).
//
// Warp DOES cooperate now, for a callable body. codegen.py appends a hidden
// trailing `const unsigned int* _wp_cond_guard` to every HIP kernel signature
// and opens the kernel with the HIPGRAPH_COND_GUARD prologue; context.py binds
// that pointer to the region's slot for launches made inside capture_while's
// body callback, and to null everywhere else. wp_hip_graph_get_guard below is
// what hands the pointer out. So a while-region whose condition is already
// false on entry does zero work: the slot is seeded from the caller's condition
// array before copy 0's dependencies are read (hipgraph_cond.cu's
// hipGraphCondBegin), so copy 0 already sees the seeded value.
//
// Three cases are still NOT predicated:
//   * a body passed as an already-captured wp.Graph -- its kernel nodes were
//     cloned with whatever guard they were captured with (null), and a graph
//     node's params cannot be rebound at splice time. context.py refuses this
//     on HIP and names the callable form as the fix.
//   * non-kernel nodes in the body (memcpy / memset / child graph). They are
//     cloned verbatim and re-run on every copy. warp.cu warns once.
//   * Warp's own built-in device kernels -- array_fill, the strided copy
//     kernels, the scan/radix-sort passes. Those are compiled into this library
//     rather than generated by codegen.py, so they carry no guard parameter and
//     nothing detects them: a kernel node in the body graph is indistinguishable
//     from a generated one. Most are idempotent once the guarded kernels stop
//     writing -- a fill, or a copy out of a now-frozen source, writes the same
//     bytes again -- so the usual cost is wasted dispatch rather than a wrong
//     answer. An IN-PLACE built-in is the exception and would accumulate. Do
//     not put one directly in a capture_while body on HIP.
// capture_if is built on the same guard, with one extra constraint of its own.
// A while-body that ignores the guard costs wasted iterations; an if/else body
// that ignores it runs the branch the condition selected AGAINST. So the three
// cases above are warnings for capture_while and hard errors for capture_if --
// see wp_cuda_graph_check_conditional_if_body in warp.cu.
//
// The adaptation is only in the shape of the call. Warp expects
//
//     insert_while(...)  ->  *body_graph_ret, *handle_ret
//     ...caller populates the body graph...
//     set_condition(..., handle)
//
// i.e. the body comes back as a GRAPH, not a stream. hipgraph_cond's native
// idiom is a body STREAM, which is why it grew hipGraphCondEndWithGraph.
//
// Measured on MI325X (gfx942, ROCm 7.2): up to 7.43x over dispatching every
// iteration, at 64M elements converging at iteration 1. The predication is
// verified rather than assumed -- effective iterations track the convergence
// point rather than the unroll bound, and replaying the same exec reproduces
// the counts, which is what catches a missing per-replay condition reset.
// That figure is hipgraph_cond's own benchmark, whose kernels read the guard.
// Warp's kernels now read it too, but the speedup is a property of the body --
// how much work a skipped copy would have done -- not of the mechanism, so it
// is NOT a number to quote for a Warp capture_while. That would be quoting
// someone else's kernels.
//
// IMPORTANT for callers: the slot pool must be reserved BEFORE a capture
// begins. A lazy allocation inside a live capture returns error 906 and kills
// the capture.

#if defined(WP_ENABLE_HIP) && WP_ENABLE_HIP

#include "hip_util.h"

// Reserve the condition-slot pool. Idempotent and cheap after the first call.
//
// Call this during setup, outside any capture. hipGraphCondHandleCreate would
// otherwise reserve lazily on first use, and that reservation allocates --
// which is illegal inside an active capture and returns 906, poisoning it.
// insert_while calls this defensively, but by then the parent stream is
// already capturing, so an explicit early call is the clean path.
bool wp_hip_graph_reserve_cond_pool(unsigned int slots);

// How many while-regions on the current device hit the end of their unroll with
// the condition still set, i.e. how many loops were silently truncated.
//
// The static unroll has an iteration bound that a real CUDA conditional node
// does not, so a loop needing more iterations than the bound stops early and
// returns an under-iterated result. Nothing portable is watching for that, so it
// is counted on device and reported here. Cumulative over the process;
// synchronize the replay before reading.
bool wp_hip_graph_query_truncations(unsigned int* count_out);

// Open a conditional (while) region on `stream` and hand Warp a graph to fill.
//
// `condition` is a device pointer to an int that the body updates; the region
// stops doing work once it reads zero. `handle_ret` receives an opaque value
// that wp_cuda_graph_set_condition later uses to re-arm the condition, matching
// the CUDA path's handle semantics.
//
// Returns false and sets the Warp error string on failure.
bool wp_hip_graph_insert_while(void* stream, int* condition, void** body_graph_ret, uint64_t* handle_ret);

// Re-arm the condition for a region opened above. Mirrors
// wp_cuda_graph_set_condition; separated so warp.cu's dispatch stays symmetric.
bool wp_hip_graph_set_condition(void* stream, int* condition, uint64_t handle);

// Begin an if/else pair on `stream` and hand Warp one graph per branch.
//
// THIS OPENS NO REGION. That is the whole trick, and it is why the shape works
// at all on HIP.
//
// Warp's contract requires BOTH body graphs back from a single call, before
// either branch has been captured -- on CUDA one cuGraphAddNode with
// conditional.size = 2 yields both. hipGraphCondBegin opens exactly one region
// on a stream and closes it with hipGraphCondEndWithGraph, and g_pending
// refuses a second open region on the same stream, so two regions cannot both
// be open before either body exists.
//
// They never have to be. The regions are needed only to SPLICE finished bodies
// into the parent, and that can be done sequentially, afterwards. So this call
// only hands out two fresh empty hipGraph_t and parks the condition pointer;
// wp_hip_graph_splice_if_else does the Begin/EndWithGraph pairs, one after the
// other, once both bodies are complete and the parent is capturing again.
//
// Pass null for a branch that is not used; at least one must be non-null.
bool wp_hip_graph_insert_if_else(void* stream, int* condition, void** if_graph_ret, void** else_graph_ret);

// Hand back the device guard word for each branch of the pending pair.
//
// Each branch gets its OWN slot, because each is predicated on a different
// value: the if branch on `condition`, the else branch on its complement. Warp
// binds the matching pointer as the hidden trailing kernel argument for
// launches made inside that branch's callback. A branch that was not requested
// reports a null guard.
bool wp_hip_graph_get_if_else_guards(void* stream, void** if_guard_ret, void** else_guard_ret);

// Splice both branch bodies into the parent graph. Call once, after both bodies
// have been captured and the parent capture has been resumed.
//
// Emits, in this order:
//   1. the complement node: scratch = !*condition
//   2. the if region -- Begin(if_handle, If, condition, 1) + EndWithGraph
//   3. the else region -- Begin(else_handle, If, scratch, 1) + EndWithGraph
//
// Step 1 comes first so that both branches test the SAME value of the condition
// even if the if-body writes to it, which is what CUDA's single two-body
// conditional node gives for free. Steps 2 and 3 are sequential: only one
// region is ever open.
bool wp_hip_graph_splice_if_else(void* stream);

// The stricter body check the if/else shape needs lives in warp.cu, next to the
// node-type machinery it shares with the CUDA path:
// wp_cuda_graph_check_conditional_if_body.

// Hand back the device guard word for a region opened by insert_while.
//
// This is the pointer every kernel in the body must test before doing work --
// see the HIPGRAPH_COND_GUARD prologue in hipgraph_cond.h, and the caveat at
// the top of this file for why the unroll is otherwise unpredicated. Warp binds
// the result as the hidden trailing kernel argument for launches made inside
// the body callback.
//
// `handle_bits` is what insert_while returned. The pointed-to word is the same
// storage as the region's condition slot, and the slot pool is never freed once
// a slot has been spliced into a graph (hipGraphCondPoolRelease refuses while
// retired slots exist), so the address stays valid for the life of the process
// -- which is what lets a graph replayed long after capture still read it.
//
// Must be called while the handle is live, i.e. between insert_while and
// set_condition; set_condition destroys the handle.
bool wp_hip_graph_get_guard(uint64_t handle_bits, void** guard_ret);

// Destroy body graphs handed out by insert_while and since finished with.
//
// They cannot be freed inside set_condition: the caller's stream is still
// capturing INTO the body graph at that point, and it calls
// wp_cuda_graph_check_conditional_body on the same pointer afterwards. Freeing
// there is a use-after-free that the failure path turns into a segfault
// (hipStreamEndCapture on a destroyed graph). Call this between captures, where
// no body graph can still be live.
void wp_hip_graph_release_body_graphs();

// Abort a region that insert_while opened and nothing ever closed.
//
// capture_while can raise between insert_while and set_condition -- the body
// callback itself can throw, and wp_cuda_graph_insert_child_graph rejects a
// graph body containing a memory allocation. Python's error path unwinds the
// capture but knows nothing about the open region, so it stays open, the parent
// capture is left unjoined, and the hipStreamEndCapture that follows fails and
// leaves the stream capturing. Every subsequent operation on that stream then
// returns 900 for the life of the process.
//
// Call this at end_capture, where a still-open region can only mean the caller
// abandoned it. Returns false only if the abort itself failed; having nothing
// to abort is the normal case and reports success.
bool wp_hip_graph_abort_open_region(void* stream);

// Bound the static unroll. Must be called before the region opens: the bound
// cannot be changed once hipGraphCondBegin has run, and Warp has no point
// between the two where it could reach in, so a bound set early is parked
// per-stream and adopted by the next region.
//
// The default (kDefaultMaxIters in hip_graph_cond.cpp, 32) is a poor fit for a solver that
// needs one iteration: it emits 32 predicated bodies and costs roughly 2x the
// unconditional graph. Callers that know their budget should set it.
bool wp_hip_graph_set_max_iters(void* stream, unsigned int max_iters);

// Declare the guard of the region that lexically encloses the next one opened on
// this stream. Parked per-stream for the same reason as set_max_iters, and
// consumed -- and erased -- by the next insert_while / insert_if_else. Pass null,
// or simply do not call it, for a top-level region.
//
// REQUIRED FOR CORRECT NESTING, not an optimisation. The unroll predicates body
// kernels but cannot predicate the seed kernels that WRITE the guards; something
// has to make the first write. When regions nest, the enclosing body graph is
// cloned into the parent and the inner region's seeds are cloned with it, and
// those clones run unconditionally -- re-arming the inner guard straight from the
// user's condition array even when the enclosing guard is 0. The inner body then
// runs inside a branch that was not taken. Measured on gfx942: test_complex_capture
// with both conditions false returned 5005 where 385 is correct, exactly 385 x 13,
// the 13x kernel being the inner else body of the suppressed branch.
//
// With a guard attached, every seed writes `(*condition != 0) && (*enclosing != 0)`.
// That composes to any depth, because each enclosing guard was itself written by a
// seed that ANDs with its own. See hipGraphCondSetEnclosingGuard in hipgraph_cond.h.
bool wp_hip_graph_set_enclosing_guard(void* stream, void* guard);

#endif  // WP_ENABLE_HIP
