// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#pragma once

// Conditional graph regions for HIP/ROCm.
//
// ROCm has no equivalent of CUDA's conditional graph node
// (CU_GRAPH_NODE_TYPE_CONDITIONAL), so Warp's capture_while / capture_if cannot
// be expressed the way warp.cu builds them: cudaGraphConditionalHandleCreate is
// bound for HIP only to return hipErrorNotSupported, and cudaGraphAddNode and
// cudaGraphNodeParams are not bound at all.
//
// This header adapts Warp's conditional-node contract onto hipgraph_cond, which
// approximates the same semantics with a static unroll: the loop body is emitted
// max_iters times into the parent graph, with a device-side refresh of the
// condition between copies, and no host round trip (a host poll is illegal
// inside a capture).
//
// READ THIS BEFORE TRUSTING THE SEMANTICS. The unroll is predicated only if the
// body cooperates. hipgraph_cond.cu::cloneGraphInto copies each body node's
// params verbatim and injects nothing, so a copy is skipped at run time only
// when the body's own kernels test the region's guard word
// (hipGraphCondSetGuard / hipGraphCondHandleGetDevicePtr).
//
// Warp DOES cooperate now, for a callable body. codegen.py appends a hidden
// trailing `const unsigned int* _wp_cond_guard` to every HIP kernel signature
// and opens the kernel with the HIPGRAPH_COND_GUARD prologue; context.py binds
// that pointer to the region's slot for launches made inside capture_while's
// body callback, and to null everywhere else. wp_hip_graph_get_guard below is
// what hands the pointer out. So a while-region whose condition is already
// false on entry does zero work: the slot is seeded from the caller's condition
// array before copy 0's dependencies are read (hipgraph_cond.cu's
// hipGraphCondBegin), so copy 0 already sees the seeded value.
//
// Three cases are still NOT predicated:
//   * a body passed as an already-captured wp.Graph -- its kernel nodes were
//     cloned with whatever guard they were captured with (null), and a graph
//     node's params cannot be rebound at splice time. context.py refuses this
//     on HIP and names the callable form as the fix.
//   * non-kernel nodes in the body (memcpy / memset / child graph). They are
//     cloned verbatim and re-run on every copy. warp.cu warns once.
//   * Warp's own built-in device kernels -- array_fill, the strided copy
//     kernels, the scan/radix-sort passes. Those are compiled into this library
//     rather than generated by codegen.py, so they carry no guard parameter and
//     nothing detects them: a kernel node in the body graph is indistinguishable
//     from a generated one. Most are idempotent once the guarded kernels stop
//     writing -- a fill, or a copy out of a now-frozen source, writes the same
//     bytes again -- so the usual cost is wasted dispatch rather than a wrong
//     answer. An IN-PLACE built-in is the exception and would accumulate. Do
//     not put one directly in a capture_while body on HIP.
// capture_if is also still refused on HIP (wp_cuda_graph_insert_if_else in
// warp.cu); the guard is the mechanism it was waiting on, but wiring
// hipGraphCondTypeIf is separate work.
//
// The adaptation is only in the shape of the call. Warp expects
//
//     insert_while(...)  ->  *body_graph_ret, *handle_ret
//     ...caller populates the body graph...
//     set_condition(..., handle)
//
// i.e. the body comes back as a GRAPH, not a stream. hipgraph_cond's native
// idiom is a body STREAM, which is why it grew hipGraphCondEndWithGraph.
//
// Measured on MI325X (gfx942, ROCm 7.2): up to 7.43x over dispatching every
// iteration, at 64M elements converging at iteration 1. The predication is
// verified rather than assumed -- effective iterations track the convergence
// point rather than the unroll bound, and replaying the same exec reproduces
// the counts, which is what catches a missing per-replay condition reset.
// That figure is hipgraph_cond's own benchmark, whose kernels read the guard.
// Warp's kernels now read it too, but the speedup is a property of the body --
// how much work a skipped copy would have done -- not of the mechanism, so it
// is NOT a number to quote for a Warp capture_while. That would be quoting
// someone else's kernels.
//
// IMPORTANT for callers: the slot pool must be reserved BEFORE a capture
// begins. A lazy allocation inside a live capture returns error 906 and kills
// the capture.

#if defined(WP_ENABLE_HIP) && WP_ENABLE_HIP

#include "hip_util.h"

// Reserve the condition-slot pool. Idempotent and cheap after the first call.
//
// Call this during setup, outside any capture. hipGraphCondHandleCreate would
// otherwise reserve lazily on first use, and that reservation allocates --
// which is illegal inside an active capture and returns 906, poisoning it.
// insert_while calls this defensively, but by then the parent stream is
// already capturing, so an explicit early call is the clean path.
bool wp_hip_graph_reserve_cond_pool(unsigned int slots);

// Open a conditional (while) region on `stream` and hand Warp a graph to fill.
//
// `condition` is a device pointer to an int that the body updates; the region
// stops doing work once it reads zero. `handle_ret` receives an opaque value
// that wp_cuda_graph_set_condition later uses to re-arm the condition, matching
// the CUDA path's handle semantics.
//
// Returns false and sets the Warp error string on failure.
bool wp_hip_graph_insert_while(void* stream, int* condition, void** body_graph_ret, uint64_t* handle_ret);

// Re-arm the condition for a region opened above. Mirrors
// wp_cuda_graph_set_condition; separated so warp.cu's dispatch stays symmetric.
bool wp_hip_graph_set_condition(void* stream, int* condition, uint64_t handle);

// Hand back the device guard word for a region opened by insert_while.
//
// This is the pointer every kernel in the body must test before doing work --
// see the HIPGRAPH_COND_GUARD prologue in hipgraph_cond.h, and the caveat at
// the top of this file for why the unroll is otherwise unpredicated. Warp binds
// the result as the hidden trailing kernel argument for launches made inside
// the body callback.
//
// `handle_bits` is what insert_while returned. The pointed-to word is the same
// storage as the region's condition slot, and the slot pool is never freed once
// a slot has been spliced into a graph (hipGraphCondPoolRelease refuses while
// retired slots exist), so the address stays valid for the life of the process
// -- which is what lets a graph replayed long after capture still read it.
//
// Must be called while the handle is live, i.e. between insert_while and
// set_condition; set_condition destroys the handle.
bool wp_hip_graph_get_guard(uint64_t handle_bits, void** guard_ret);

// Destroy body graphs handed out by insert_while and since finished with.
//
// They cannot be freed inside set_condition: the caller's stream is still
// capturing INTO the body graph at that point, and it calls
// wp_cuda_graph_check_conditional_body on the same pointer afterwards. Freeing
// there is a use-after-free that the failure path turns into a segfault
// (hipStreamEndCapture on a destroyed graph). Call this between captures, where
// no body graph can still be live.
void wp_hip_graph_release_body_graphs();

// Abort a region that insert_while opened and nothing ever closed.
//
// capture_while can raise between insert_while and set_condition -- the body
// callback itself can throw, and wp_cuda_graph_insert_child_graph rejects a
// graph body containing a memory allocation. Python's error path unwinds the
// capture but knows nothing about the open region, so it stays open, the parent
// capture is left unjoined, and the hipStreamEndCapture that follows fails and
// leaves the stream capturing. Every subsequent operation on that stream then
// returns 900 for the life of the process.
//
// Call this at end_capture, where a still-open region can only mean the caller
// abandoned it. Returns false only if the abort itself failed; having nothing
// to abort is the normal case and reports success.
bool wp_hip_graph_abort_open_region(void* stream);

// Bound the static unroll. Must be called before the region opens: the bound
// cannot be changed once hipGraphCondBegin has run, and Warp has no point
// between the two where it could reach in, so a bound set early is parked
// per-stream and adopted by the next region.
//
// The default (kDefaultMaxIters in hip_graph_cond.cpp, 32) is a poor fit for a solver that
// needs one iteration: it emits 32 predicated bodies and costs roughly 2x the
// unconditional graph. Callers that know their budget should set it.
bool wp_hip_graph_set_max_iters(void* stream, unsigned int max_iters);

#endif  // WP_ENABLE_HIP
